---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/account/login":
    post:
      summary: Login an account
      tags:
      - acore_auth
      parameters: []
      responses:
        '200':
          description: login successful
          content: {}
        '401':
          description: wrong password
          content: {}
        '404':
          description: account not found
          content: {}
        '500':
          description: error
          content: {}
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
              required:
              - username
              - password
  "/account/register":
    post:
      summary: Register an account
      tags:
      - acore_auth
      parameters: []
      responses:
        '201':
          description: account created
          content: {}
        '403':
          description: username is taken
          content: {}
        '404':
          description: email is taken
          content: {}
        '500':
          description: error
          content: {}
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
                email:
                  type: string
              required:
              - username
              - password
              - email
  "/characters/all":
    get:
      summary: All Characters
      tags:
      - acore_characters
      responses:
        '200':
          description: success
          content: {}
        '500':
          description: error
          content: {}
  "/characters/get/":
    post:
      summary: Get a single Character
      tags:
      - acore_characters
      parameters: []
      responses:
        '200':
          description: success
          content: {}
        '500':
          description: error
          content: {}
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                guid:
                  type: integer
              required:
              - guid
  "/news/create":
    post:
      summary: Create New Article
      tags:
      - local
      parameters: []
      responses:
        '201':
          description: success
          content: {}
        '500':
          description: error
          content: {}
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                content:
                  type: string
              required:
              - title
              - content
  "/news/get":
    post:
      summary: Get single Article
      tags:
      - local
      parameters: []
      responses:
        '200':
          description: success
          content: {}
        '500':
          description: error
          content: {}
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                slug:
                  type: string
              required:
              - slug
  "/news":
    get:
      summary: Get all News Articles
      tags:
      - local
      responses:
        '200':
          description: success
          content: {}
        '500':
          description: error
          content: {}
  "/realm/info":
    get:
      summary: Realm Info
      tags:
      - acore_auth
      responses:
        '200':
          description: success
          examples:
            application/json:
              id: 1
              title: Hello world!
              content: "..."
          content: {}
        '500':
          description: error
          content: {}
  "/realm/uptime":
    get:
      summary: Realm Uptime
      tags:
      - acore_auth
      responses:
        '200':
          description: success
          content: {}
        '500':
          description: error
          content: {}
  "/realm/characters":
    get:
      summary: Realm Characters
      tags:
      - acore_auth
      responses:
        '200':
          description: success
          content: {}
        '500':
          description: error
          content: {}
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:5000
