default: &default
  adapter: mysql2
  encoding: utf8
  pool: 10
  
development:
  <<: *default
  url: <%= ENV['AUTH_DATABASE_URL'] %>

production:
  <<: *default
  url: <%= ENV['AUTH_DATABASE_URL'] %>