# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will download a prebuilt Ruby version, install dependencies and run tests with Rake
# For more information see: https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby

name: Ruby

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: CI
    runs-on: ubuntu-latest
    
    steps:
      - uses: mirromutth/mysql-action@v1.1
        with:
          mysql version: "5.7.17"
          mysql root password: "password"

      - uses: actions/checkout@v2
      - name: Set up Ruby
      # To automatically get bug fixes and new Ruby versions for ruby/setup-ruby,
      # change this to (see https://github.com/ruby/setup-ruby#versioning):
        uses: ruby/setup-ruby@v1
        # uses: ruby/setup-ruby@ec106b438a1ff6ff109590de34ddc62c540232e0
        with:
          ruby-version: 2.6.6
        
      - uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-:  
      
      - name: Bundle Install and Create DB
        env:
          RAILS_ENV: test
          DB_PASSWORD: password
          # tell Rails to use proper port for MySQL
          DB_PORT: ${{ job.services.mysql.ports[3306] }}
        run: |
          gem install bundler --no-ri --no-rdoc
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3 --path vendor/bundle
          # create DB for Rails 5.x
          bin/rails db:setup

   
